language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "rYq9sMV/uKXPgJr7PBaCaSFOGKxUz4cYil3VNUlO5ANrOWlzEZf1Rv8r0YpIPa0jaogybbMSQW4XD8CSNsuUKGNGK0PFSr22sHQLzKiogZ+mXwkYqxoytDMVcXASTgm7p1fVe2QoAz73iu6K0z4+bXRT1SLnHsDgbxcoalYqNNQ+Sj5j+PxWg6P7h9ZbZ1ojh0ADU1f5gFXfT10ReVwexVUeNwqjGiN7/UNlj+mEQGKQSuKKTwDRwn/dsAnL/PhIWiBVURNb9bg6m7kfFXQuzS5svJoqrrMabnZq1oXRltDF7xaqojd/9KqwlD2V8ZVaG6Y0yRJfOMiacxMVb/T34C1uLTtYXNcHEySb+ovbfwfbc4nci8G3s+WRy14R+LmUz0bQqGYoOWnK98WBScv8PbWNMJi1OWwy8kuuQ0JaOFIODYKc22OZu+zvj8E7YdqLcF9NxYy71YH2WyP5sIwsPjEbFn41pDsryZ83KdD4KWR6b0mdnPSBK/VdzwF35Bwm0Ou8ytFXmfDIcHgpj9LXmhCKaMMoyaEIbnIug6T/tFaIgMNSnYrCXkbrMRK+1lygfYzk8nzBM7a8fER+WO6FDbtI4VCB5H8WExxLE9Fo+glEzmbbKo6yiQ/LoojROfOYILSrn7rstfM3bV2sRzIcgfDUmjFGYh5s3TPdz+6LV7g="