language: node_js
node_js:
  - "8.11.4"
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - env: FrontEnd
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/frontend
        - npm install -g @angular/cli
        - npm install -g firebase-tools
      script:
        - npm install
        - firebase use production 
        - npm run build:production
      after_success:
        - firebase deploy --only hosting,storage --token $FIREBASE_TOKEN --non-interactive
    - env: BackEnd
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/backend/service-accounts
        - openssl aes-256-cbc -K $encrypted_fa719de7ed26_key -iv $encrypted_fa719de7ed26_iv -in production.json.enc -out production.json -d
        - cd ${TRAVIS_BUILD_DIR}/backend
        - npm install -g @angular/cli
        - npm install -g firebase-tools
      script:
        - npm install
        - firebase use production 
        - firebase functions:config:set env.value="production"
        - firebase deploy --only functions --token $FIREBASE_TOKEN --non-interactive